#!/usr/bin/env python3
"""
Remove `villager_house` and `villager_farm` regions, replace floor at Y=78 with dirt,
clear structures above Y=78 to air, and clear all dropped loot.

Supports --undo and --dry-run for strict rollback compliance.
"""

import os
import sys
import json
import yaml
import subprocess
import argparse

REGIONS_FILE = "WorldGuard/worlds/world/regions.yml"
REGISTRY_FILE = "player_regions_registry.json"

BACKUP_DIR = "WorldGuard/backups"
BACKUP_REGIONS = os.path.join(BACKUP_DIR, "remove_villagers_regions_backup.yml")
BACKUP_REGISTRY = os.path.join(BACKUP_DIR, "remove_villagers_registry_backup.json")

HEADER_COMMENTS = """#
# WorldGuard regions file
#
# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by
# hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE. If
# WorldGuard is unable to parse the file, your regions will FAIL TO LOAD and
# the contents of this file will reset. Please use a YAML validator such as
# http://yaml-online-parser.appspot.com (for smaller files).
#
# REMEMBER TO KEEP PERIODICAL BACKUPS.
#
"""

MIN_X, MAX_X = 1293, 1300
MIN_Z, MAX_Z = -239, -222
FLOOR_Y = 78
CLEAR_MAX_Y = 92

def get_credentials():
    ENV_FILE = ".env"
    config = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip()

    token = os.environ.get("EXAROTON_TOKEN") or config.get("EXAROTON_TOKEN") or "NovL7NzAL8zzsWVKIxC1JFAdVOoQfpI3ej7oyorsHlLVOe0joLeiJ7aopethRcSUrED0p2dqkz1RxfPaZKGV31un15PrdP8Zk4RJ"
    server_id = os.environ.get("EXAROTON_SERVER_ID") or config.get("EXAROTON_SERVER_ID") or "cEuS61sZvNEFS3aB"
    return token, server_id

def send_exaroton_command(cmd, dry_run=False):
    if dry_run:
        print(f"[DRY-RUN] Console Command: {cmd}")
        return True

    token, server_id = get_credentials()
    url = f"https://api.exaroton.com/v1/servers/{server_id}/command/"
    curl_cmd = [
        "curl", "-s",
        "--resolve", "api.exaroton.com:443:104.26.12.211",
        "-X", "POST", url,
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"command": cmd})
    ]
    res = subprocess.run(curl_cmd, capture_output=True, text=True)
    try:
        data = json.loads(res.stdout)
        return data.get("success", False)
    except Exception:
        return False

def backup():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    if os.path.exists(REGIONS_FILE):
        with open(REGIONS_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGIONS, "w") as f:
            f.write(content)
        print(f"Backed up {REGIONS_FILE} to {BACKUP_REGIONS}")

    if os.path.exists(REGISTRY_FILE):
        with open(REGISTRY_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGISTRY, "w") as f:
            f.write(content)
        print(f"Backed up {REGISTRY_FILE} to {BACKUP_REGISTRY}")

def execute_removal(dry_run=False):
    if not os.path.exists(REGIONS_FILE) or not os.path.exists(REGISTRY_FILE):
        print("[ERROR] Required config files do not exist locally.")
        return False

    backup()

    # 1. Update regions.yml
    with open(REGIONS_FILE, "r") as f:
        regions_data = yaml.safe_load(f) or {}

    removed_regions = []
    if "regions" in regions_data:
        for r_name in ["villager_house", "villager_farm"]:
            if r_name in regions_data["regions"]:
                if not dry_run:
                    del regions_data["regions"][r_name]
                removed_regions.append(r_name)

    # 2. Update player_regions_registry.json
    with open(REGISTRY_FILE, "r") as f:
        registry_data = json.load(f)

    removed_registry = []
    if "regions" in registry_data:
        for r_name in ["villager_house", "villager_farm"]:
            if r_name in registry_data["regions"]:
                if not dry_run:
                    del registry_data["regions"][r_name]
                removed_registry.append(r_name)

    if dry_run:
        print(f"[DRY-RUN] Would remove regions from files: {removed_regions}")
    else:
        with open(REGIONS_FILE, "w") as f:
            f.write(HEADER_COMMENTS)
            yaml.safe_dump(regions_data, f, default_flow_style=False, indent=4)

        with open(REGISTRY_FILE, "w") as f:
            json.dump(registry_data, f, indent=4)
        print(f"Locally removed regions: {removed_regions}")

    # 3. Sync configs to server and reload WorldGuard
    if not dry_run:
        print("Pushing updated configuration files to server...")
        subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
        subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)
        print("Reloading WorldGuard plugin on the server...")
        send_exaroton_command("wg reload")
    else:
        print("[DRY-RUN] Would push configs and reload WorldGuard.")

    # 4. Modify World blocks
    # Clear volume above floor (Y=79 to 92)
    clear_cmd = f"fill {MIN_X} 79 {MIN_Z} {MAX_X} {CLEAR_MAX_Y} {MAX_Z} minecraft:air"
    # Fill floor at Y=78 with dirt path
    dirt_cmd = f"fill {MIN_X} {FLOOR_Y} {MIN_Z} {MAX_X} {FLOOR_Y} {MAX_Z} minecraft:dirt_path"
    # Clear dropped loot
    loot_cmd = f"kill @e[type=item,x=1296,y=78,z=-230,distance=..30]"

    print("Running world modification commands...")
    send_exaroton_command(clear_cmd, dry_run=dry_run)
    send_exaroton_command(dirt_cmd, dry_run=dry_run)
    send_exaroton_command(loot_cmd, dry_run=dry_run)

    print("Execution complete!")
    return True

def undo(dry_run=False):
    if not os.path.exists(BACKUP_REGIONS) or not os.path.exists(BACKUP_REGISTRY):
        print("[ERROR] Backups not found to undo.")
        return False

    if dry_run:
        print("[DRY-RUN] Would restore backups for regions.yml and registry.")
        print("[DRY-RUN] Would restore floor to white concrete at Y=78.")
        return True

    # Restore files
    with open(BACKUP_REGIONS, "r") as sf, open(REGIONS_FILE, "w") as df:
        df.write(sf.read())
    with open(BACKUP_REGISTRY, "r") as sf, open(REGISTRY_FILE, "w") as df:
        df.write(sf.read())

    print("Restored local backup files.")

    # Push to server
    print("Pushing restored files to server...")
    subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
    subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    print("Reloading WorldGuard plugin on the server...")
    send_exaroton_command("wg reload")

    # Restore floor to white_concrete
    concrete_cmd = f"fill {MIN_X} {FLOOR_Y} {MIN_Z} {MAX_X} {FLOOR_Y} {MAX_Z} minecraft:white_concrete"
    loot_cmd = f"kill @e[type=item,x=1296,y=78,z=-230,distance=..30]"
    print("Restoring floor blocks on server...")
    send_exaroton_command(concrete_cmd)
    send_exaroton_command(loot_cmd)

    print("Undo completed successfully!")
    return True

def main():
    parser = argparse.ArgumentParser(description="Remove villager regions and change floor to dirt.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without saving.")
    parser.add_argument("--undo", action="store_true", help="Restore previous bounds and blocks.")
    args = parser.parse_args()

    if args.undo:
        undo(dry_run=args.dry_run)
    else:
        execute_removal(dry_run=args.dry_run)

if __name__ == "__main__":
    main()
