#!/usr/bin/env python3
"""
Rename region `combined_region` to `villager_house` in WorldGuard/worlds/world/regions.yml
and player_regions_registry.json, and make it owned by noone (clear owners/members).

Supports --undo and --dry-run options.
"""

import os
import sys
import json
import yaml
import subprocess
import argparse

REGIONS_FILE = "WorldGuard/worlds/world/regions.yml"
REGISTRY_FILE = "player_regions_registry.json"

BACKUP_DIR = "WorldGuard/backups"
BACKUP_REGIONS = os.path.join(BACKUP_DIR, "rename_villager_house_regions_backup.yml")
BACKUP_REGISTRY = os.path.join(BACKUP_DIR, "rename_villager_house_registry_backup.json")

HEADER_COMMENTS = """#
# WorldGuard regions file
#
# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by
# hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE. If
# WorldGuard is unable to parse the file, your regions will FAIL TO LOAD and
# the contents of this file will reset. Please use a YAML validator such as
# http://yaml-online-parser.appspot.com (for smaller files).
#
# REMEMBER TO KEEP PERIODICAL BACKUPS.
#
"""

def send_exaroton_command(cmd, dry_run=False):
    if dry_run:
        print(f"[DRY-RUN] Console Command: {cmd}")
        return True

    ENV_FILE = ".env"
    config = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip()

    token = os.environ.get("EXAROTON_TOKEN") or config.get("EXAROTON_TOKEN") or "NovL7NzAL8zzsWVKIxC1JFAdVOoQfpI3ej7oyorsHlLVOe0joLeiJ7aopethRcSUrED0p2dqkz1RxfPaZKGV31un15PrdP8Zk4RJ"
    server_id = os.environ.get("EXAROTON_SERVER_ID") or config.get("EXAROTON_SERVER_ID") or "cEuS61sZvNEFS3aB"

    url = f"https://api.exaroton.com/v1/servers/{server_id}/command/"
    curl_cmd = [
        "curl", "-s",
        "--resolve", "api.exaroton.com:443:104.26.12.211",
        "-X", "POST", url,
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"command": cmd})
    ]
    res = subprocess.run(curl_cmd, capture_output=True, text=True)
    try:
        data = json.loads(res.stdout)
        if not data.get("success", False):
            print(f"[ERROR] Exaroton Command Failed: {data.get('error')}")
            return False
        return True
    except Exception as e:
        print(f"[ERROR] Failed to parse API response: {res.stdout}")
        return False

def backup():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    # Backup regions.yml
    if os.path.exists(REGIONS_FILE):
        with open(REGIONS_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGIONS, "w") as f:
            f.write(content)
        print(f"Backed up {REGIONS_FILE} to {BACKUP_REGIONS}")

    # Backup registry
    if os.path.exists(REGISTRY_FILE):
        with open(REGISTRY_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGISTRY, "w") as f:
            f.write(content)
        print(f"Backed up {REGISTRY_FILE} to {BACKUP_REGISTRY}")

def rename_to_villager_house(dry_run=False):
    if not os.path.exists(REGIONS_FILE):
        print(f"[ERROR] Regions file not found: {REGIONS_FILE}")
        return False
    if not os.path.exists(REGISTRY_FILE):
        print(f"[ERROR] Registry file not found: {REGISTRY_FILE}")
        return False

    backup()

    # Load regions.yml
    with open(REGIONS_FILE, "r") as f:
        regions_data = yaml.safe_load(f) or {}

    if "regions" not in regions_data or "combined_region" not in regions_data["regions"]:
        print("[ERROR] 'combined_region' not found in regions.yml")
        return False

    # Load registry
    with open(REGISTRY_FILE, "r") as f:
        registry_data = json.load(f)

    if "regions" not in registry_data or "combined_region" not in registry_data["regions"]:
        print("[ERROR] 'combined_region' not found in player_regions_registry.json")
        return False

    if dry_run:
        print("[DRY-RUN] Would perform the following changes:")
        print("  - Rename 'combined_region' to 'villager_house' in WorldGuard/worlds/world/regions.yml")
        print("  - Clear owners and members of 'villager_house' in WorldGuard/worlds/world/regions.yml")
        print("  - Rename 'combined_region' to 'villager_house' in player_regions_registry.json")
        print("  - Remove player ownership keys from 'villager_house' in player_regions_registry.json")
        return True

    # 1. Modify regions.yml data
    region_info = regions_data["regions"].pop("combined_region")
    region_info["owners"] = {}
    region_info["members"] = {}
    regions_data["regions"]["villager_house"] = region_info

    # Write regions.yml with header
    with open(REGIONS_FILE, "w") as f:
        f.write(HEADER_COMMENTS)
        yaml.safe_dump(regions_data, f, default_flow_style=False, indent=4)

    # 2. Modify player_regions_registry.json
    registry_info = registry_data["regions"].pop("combined_region")
    # Remove player ownership keys
    registry_info.pop("player_name", None)
    registry_info.pop("owners", None)
    registry_info.pop("raw_uuids", None)
    registry_info.pop("username", None)
    registry_info.pop("uuid", None)
    registry_data["regions"]["villager_house"] = registry_info

    with open(REGISTRY_FILE, "w") as f:
        json.dump(registry_data, f, indent=4)

    print("Successfully renamed region locally.")

    # 3. Sync to Exaroton
    print("Pushing updated files to server...")
    subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
    subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    print("Reloading WorldGuard plugin on the server...")
    send_exaroton_command("wg reload")
    print("Done!")
    return True

def undo(dry_run=False):
    if not os.path.exists(BACKUP_REGIONS) or not os.path.exists(BACKUP_REGISTRY):
        print(f"[ERROR] Backup files not found.")
        return False

    if dry_run:
        print("[DRY-RUN] Would restore backup files for regions and registry.")
        return True

    # Restore files
    with open(BACKUP_REGIONS, "r") as sf, open(REGIONS_FILE, "w") as df:
        df.write(sf.read())
    with open(BACKUP_REGISTRY, "r") as sf, open(REGISTRY_FILE, "w") as df:
        df.write(sf.read())

    print("Restored local backup files.")

    # Push to server
    print("Pushing restored files to server...")
    subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
    subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    print("Reloading WorldGuard plugin on the server...")
    send_exaroton_command("wg reload")
    print("Undo completed successfully!")
    return True

def main():
    parser = argparse.ArgumentParser(description="Rename combined_region to villager_house and make owned by noone.")
    parser.add_argument("--dry-run", action="store_true", help="Show changes without applying them.")
    parser.add_argument("--undo", action="store_true", help="Restore the backup files to undo changes.")
    args = parser.parse_args()

    if args.undo:
        undo(dry_run=args.dry_run)
    else:
        rename_to_villager_house(dry_run=args.dry_run)

if __name__ == "__main__":
    main()
