#!/usr/bin/env python3
"""
Separate the villager claim into two regions:
1. `villager_house` (X: 1293..1300, Y: 78..92, Z: -230..-222) - Fully protected house area.
2. `villager_farm` (X: 1293..1300, Y: 78..92, Z: -239..-231) - Farm area with 'build: allow',
   'interact: allow', and 'mob-griefing: allow' flags to let players and villagers farm.

Updates regions.yml and player_regions_registry.json.
Supports --undo and --dry-run.
"""

import os
import sys
import json
import yaml
import subprocess
import argparse

REGIONS_FILE = "WorldGuard/worlds/world/regions.yml"
REGISTRY_FILE = "player_regions_registry.json"

BACKUP_DIR = "WorldGuard/backups"
BACKUP_REGIONS = os.path.join(BACKUP_DIR, "farm_permissions_regions_backup.yml")
BACKUP_REGISTRY = os.path.join(BACKUP_DIR, "farm_permissions_registry_backup.json")

HEADER_COMMENTS = """#
# WorldGuard regions file
#
# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by
# hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE. If
# WorldGuard is unable to parse the file, your regions will FAIL TO LOAD and
# the contents of this file will reset. Please use a YAML validator such as
# http://yaml-online-parser.appspot.com (for smaller files).
#
# REMEMBER TO KEEP PERIODICAL BACKUPS.
#
"""

def send_exaroton_command(cmd, dry_run=False):
    if dry_run:
        print(f"[DRY-RUN] Console Command: {cmd}")
        return True

    ENV_FILE = ".env"
    config = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip()

    token = os.environ.get("EXAROTON_TOKEN") or config.get("EXAROTON_TOKEN") or "NovL7NzAL8zzsWVKIxC1JFAdVOoQfpI3ej7oyorsHlLVOe0joLeiJ7aopethRcSUrED0p2dqkz1RxfPaZKGV31un15PrdP8Zk4RJ"
    server_id = os.environ.get("EXAROTON_SERVER_ID") or config.get("EXAROTON_SERVER_ID") or "cEuS61sZvNEFS3aB"

    url = f"https://api.exaroton.com/v1/servers/{server_id}/command/"
    curl_cmd = [
        "curl", "-s",
        "--resolve", "api.exaroton.com:443:104.26.12.211",
        "-X", "POST", url,
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"command": cmd})
    ]
    res = subprocess.run(curl_cmd, capture_output=True, text=True)
    try:
        data = json.loads(res.stdout)
        return data.get("success", False)
    except Exception:
        return False

def backup():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    # Backup regions.yml
    if os.path.exists(REGIONS_FILE):
        with open(REGIONS_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGIONS, "w") as f:
            f.write(content)
        print(f"Backed up {REGIONS_FILE} to {BACKUP_REGIONS}")

    # Backup registry
    if os.path.exists(REGISTRY_FILE):
        with open(REGISTRY_FILE, "r") as f:
            content = f.read()
        with open(BACKUP_REGISTRY, "w") as f:
            f.write(content)
        print(f"Backed up {REGISTRY_FILE} to {BACKUP_REGISTRY}")

def setup_permissions(dry_run=False):
    if not os.path.exists(REGIONS_FILE) or not os.path.exists(REGISTRY_FILE):
        print("[ERROR] Required config files do not exist locally.")
        return False

    backup()

    # Load regions.yml
    with open(REGIONS_FILE, "r") as f:
        regions_data = yaml.safe_load(f) or {}

    if "regions" not in regions_data or "villager_house" not in regions_data["regions"]:
        print("[ERROR] 'villager_house' not found in regions.yml")
        return False

    # Load registry
    with open(REGISTRY_FILE, "r") as f:
        registry_data = json.load(f)

    if "regions" not in registry_data or "villager_house" not in registry_data["regions"]:
        print("[ERROR] 'villager_house' not found in player_regions_registry.json")
        return False

    if dry_run:
        print("[DRY-RUN] Would separate regions:")
        print("  - 'villager_house' bounds restored to Z: -230..-222 (fully protected)")
        print("  - 'villager_farm' created with Z: -239..-231 (build: allow, interact: allow, mob-griefing: allow)")
        return True

    # 1. Modify regions.yml
    # Restore villager_house bounds
    regions_data["regions"]["villager_house"]["min"]["z"] = -230

    # Create villager_farm region
    regions_data["regions"]["villager_farm"] = {
        "min": {"x": 1293, "y": 78, "z": -239},
        "max": {"x": 1300, "y": 92, "z": -231},
        "members": {},
        "owners": {},
        "flags": {
            "build": "allow",
            "interact": "allow",
            "mob-griefing": "allow",
            "creeper-explosion": "deny",
            "other-explosion": "deny",
            "tnt": "deny",
            "pvp": "allow"
        },
        "type": "cuboid",
        "priority": 0
    }

    with open(REGIONS_FILE, "w") as f:
        f.write(HEADER_COMMENTS)
        yaml.safe_dump(regions_data, f, default_flow_style=False, indent=4)

    # 2. Modify player_regions_registry.json
    # Restore villager_house registry
    house_reg = registry_data["regions"]["villager_house"]
    house_reg["min_corner"]["z"] = -230
    house_reg["dimensions"]["length_z"] = 9
    house_reg["surface_area_sq_blocks"] = 72
    house_reg["size_category"] = "Starter / Base Plot"

    # Add villager_farm registry
    registry_data["regions"]["villager_farm"] = {
        "min_corner": {"x": 1293, "y": 78, "z": -239},
        "max_corner": {"x": 1300, "y": 92, "z": -231},
        "dimensions": {"width_x": 8, "length_z": 9, "height_y": 15},
        "surface_area_sq_blocks": 72,
        "size_category": "Starter / Base Plot",
        "floor_y_level": 78,
        "floor_material": "minecraft:white_concrete"
    }

    with open(REGISTRY_FILE, "w") as f:
        json.dump(registry_data, f, indent=4)

    print("Locally updated regions and registry.")

    # 3. Push and reload
    print("Pushing updated files to server...")
    subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
    subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    print("Reloading WorldGuard plugin on the server...")
    send_exaroton_command("wg reload")
    print("Done!")
    return True

def undo(dry_run=False):
    if not os.path.exists(BACKUP_REGIONS) or not os.path.exists(BACKUP_REGISTRY):
        print("[ERROR] Backups not found to undo.")
        return False

    if dry_run:
        print("[DRY-RUN] Would restore backups for regions.yml and registry.")
        return True

    # Restore files
    with open(BACKUP_REGIONS, "r") as sf, open(REGIONS_FILE, "w") as df:
        df.write(sf.read())
    with open(BACKUP_REGISTRY, "r") as sf, open(REGISTRY_FILE, "w") as df:
        df.write(sf.read())

    print("Restored local backup files.")

    # Push to server
    print("Pushing restored files to server...")
    subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
    subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    print("Reloading WorldGuard plugin on the server...")
    send_exaroton_command("wg reload")
    print("Undo completed successfully!")
    return True

def main():
    parser = argparse.ArgumentParser(description="Configure villager farm permissions.")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without applying.")
    parser.add_argument("--undo", action="store_true", help="Revert permissions setup.")
    args = parser.parse_args()

    if args.undo:
        undo(dry_run=args.dry_run)
    else:
        setup_permissions(dry_run=args.dry_run)

if __name__ == "__main__":
    main()
