#!/usr/bin/env python3
"""
Convert the farm area of the villager region into a beautiful mini jungle biome,
remove build/interact/mob-griefing permissions so it is protected, and clear any dropped items.

Farm bounds:
X: 1293 to 1300
Z: -239 to -231
Y Floor: 78
Y Height: 79 to 92

Features:
- Set biome to minecraft:jungle
- Replace floor with grass blocks, moss, and coarse dirt
- Build 2 custom mini jungle trees with jungle logs, leaves, vines, and cocoa beans
- Add ground foliage (ferns, large ferns, bamboo, and jungle saplings)
- Remove WorldGuard build/interact/mob-griefing flags to secure it
- Updates regions.yml and player_regions_registry.json
- Clear dropped item entities

Supports --undo and --dry-run.
"""

import os
import sys
import json
import yaml
import subprocess
import argparse

BACKUP_FILE = "WorldGuard/backups/mini_jungle_build_history.json"
REGIONS_FILE = "WorldGuard/worlds/world/regions.yml"
REGISTRY_FILE = "player_regions_registry.json"

HEADER_COMMENTS = """#
# WorldGuard regions file
#
# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by
# hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE. If
# WorldGuard is unable to parse the file, your regions will FAIL TO LOAD and
# the contents of this file will reset. Please use a YAML validator such as
# http://yaml-online-parser.appspot.com (for smaller files).
#
# REMEMBER TO KEEP PERIODICAL BACKUPS.
#
"""

ENV_FILE = ".env"
CONFIG = {}
if os.path.exists(ENV_FILE):
    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                k, v = line.split("=", 1)
                CONFIG[k.strip()] = v.strip()

TOKEN = os.environ.get("EXAROTON_TOKEN") or CONFIG.get("EXAROTON_TOKEN") or "NovL7NzAL8zzsWVKIxC1JFAdVOoQfpI3ej7oyorsHlLVOe0joLeiJ7aopethRcSUrED0p2dqkz1RxfPaZKGV31un15PrdP8Zk4RJ"
SERVER_ID = os.environ.get("EXAROTON_SERVER_ID") or CONFIG.get("EXAROTON_SERVER_ID") or "cEuS61sZvNEFS3aB"

MIN_X, MAX_X = 1293, 1300
MIN_Z, MAX_Z = -239, -231
Y_FLOOR = 78

def send_exaroton_command(cmd, dry_run=False):
    if dry_run:
        print(f"[DRY-RUN] Console Command: {cmd}")
        return True

    url = f"https://api.exaroton.com/v1/servers/{SERVER_ID}/command/"
    curl_cmd = [
        "curl", "-s",
        "--resolve", "api.exaroton.com:443:104.26.12.211",
        "-X", "POST", url,
        "-H", f"Authorization: Bearer {TOKEN}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"command": cmd})
    ]
    res = subprocess.run(curl_cmd, capture_output=True, text=True)
    try:
        data = json.loads(res.stdout)
        return data.get("success", False)
    except Exception:
        return False

def build_jungle(dry_run=False):
    print("=== Converting Farm to Mini Jungle ===")

    cmds = []

    # 0. Clear farm items and air above Y=78
    cmds.append(f"fill {MIN_X} 79 {MIN_Z} {MAX_X} 92 {MAX_Z} minecraft:air")

    # 1. Biome change
    cmds.append(f"fillbiome {MIN_X} 78 {MIN_Z} {MAX_X} 92 {MAX_Z} minecraft:jungle")

    # 2. Floor blocks mix (Y=78)
    cmds.append(f"fill {MIN_X} 78 {MIN_Z} {MAX_X} 78 {MAX_Z} minecraft:grass_block")
    # Add some moss blocks
    cmds.append(f"setblock 1294 78 -238 minecraft:moss_block")
    cmds.append(f"setblock 1297 78 -236 minecraft:moss_block")
    cmds.append(f"setblock 1298 78 -233 minecraft:moss_block")
    # Add some coarse dirt
    cmds.append(f"setblock 1295 78 -237 minecraft:coarse_dirt")
    cmds.append(f"setblock 1298 78 -235 minecraft:coarse_dirt")

    # 3. Custom Tree 1 (X=1295, Z=-236)
    cmds.append(f"fill 1295 79 -236 1295 82 -236 minecraft:jungle_log")
    cmds.append(f"fill 1294 82 -237 1296 82 -235 minecraft:jungle_leaves")
    cmds.append(f"fill 1294 83 -237 1296 83 -235 minecraft:jungle_leaves")
    cmds.append(f"setblock 1295 84 -236 minecraft:jungle_leaves")
    # Vines and cocoa
    cmds.append(f"setblock 1295 80 -235 minecraft:cocoa[age=2,facing=south]")
    cmds.append(f"setblock 1294 81 -236 minecraft:vine[east=true]")
    cmds.append(f"setblock 1296 81 -236 minecraft:vine[west=true]")

    # 4. Custom Tree 2 (X=1298, Z=-234)
    cmds.append(f"fill 1298 79 -234 1298 81 -234 minecraft:jungle_log")
    cmds.append(f"fill 1297 81 -235 1299 81 -233 minecraft:jungle_leaves")
    cmds.append(f"fill 1297 82 -235 1299 82 -233 minecraft:jungle_leaves")
    cmds.append(f"setblock 1298 83 -234 minecraft:jungle_leaves")
    # Vines and cocoa
    cmds.append(f"setblock 1298 80 -235 minecraft:cocoa[age=2,facing=north]")
    cmds.append(f"setblock 1298 80 -233 minecraft:vine[north=true]")

    # 5. Lush foliage
    cmds.append(f"setblock 1294 79 -238 minecraft:jungle_sapling")
    cmds.append(f"setblock 1297 79 -238 minecraft:fern")
    cmds.append(f"setblock 1294 79 -232 minecraft:large_fern[half=lower]")
    cmds.append(f"setblock 1294 80 -232 minecraft:large_fern[half=upper]")
    # Bamboo
    cmds.append(f"setblock 1299 79 -238 minecraft:bamboo[age=1,leaves=large,stage=1]")
    cmds.append(f"setblock 1299 80 -238 minecraft:bamboo[age=1,leaves=large,stage=1]")
    cmds.append(f"setblock 1299 81 -238 minecraft:bamboo[age=1,leaves=none,stage=1]")

    # 6. Clean up dropped loot/items
    cmds.append(f"kill @e[type=item,x=1296,y=78,z=-235,distance=..20]")

    if dry_run:
        print(f"[DRY-RUN] Would run {len(cmds)} commands to build jungle.")
        for cmd in cmds[:5]:
            print(f"  {cmd}")
        print("  ...")
        return True

    # Run block commands in parallel
    import concurrent.futures
    print("Clearing farm blocks...")
    send_exaroton_command(cmds[0])
    
    print("Building mini jungle...")
    success_count = 1
    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        results = executor.map(send_exaroton_command, cmds[1:])
        for res in results:
            if res:
                success_count += 1
    print(f"Executed {success_count}/{len(cmds)} commands successfully on server.")

    # 7. Modify permissions in regions.yml (Remove build, interact, mob-griefing flags)
    print("Updating WorldGuard region configurations...")
    if os.path.exists(REGIONS_FILE):
        with open(REGIONS_FILE, "r") as f:
            regions_data = yaml.safe_load(f) or {}

        if "regions" in regions_data and "villager_farm" in regions_data["regions"]:
            flags = regions_data["regions"]["villager_farm"].get("flags", {})
            flags.pop("build", None)
            flags.pop("interact", None)
            flags.pop("mob-griefing", None)
            
            with open(REGIONS_FILE, "w") as f:
                f.write(HEADER_COMMENTS)
                yaml.safe_dump(regions_data, f, default_flow_style=False, indent=4)
            
            # Sync to server
            subprocess.run(["python3", "sync.py", "push", REGIONS_FILE], check=True)
            send_exaroton_command("wg reload")

    # 8. Update player_regions_registry.json description
    print("Updating player region registry...")
    if os.path.exists(REGISTRY_FILE):
        with open(REGISTRY_FILE, "r") as f:
            registry_data = json.load(f)

        if "regions" in registry_data and "villager_farm" in registry_data["regions"]:
            reg_info = registry_data["regions"]["villager_farm"]
            reg_info["structures"] = {
                "jungle": {
                    "bounds": {
                        "min": {"x": 1293, "y": 78, "z": -239},
                        "max": {"x": 1300, "y": 84, "z": -231}
                    },
                    "description": "Mini jungle biome zone with custom jungle trees, leaves, vines, bamboo, ferns, and cocoa beans."
                }
            }
            with open(REGISTRY_FILE, "w") as f:
                json.dump(registry_data, f, indent=4)
            
            # Sync to server
            subprocess.run(["python3", "sync.py", "push", REGISTRY_FILE], check=True)

    # 9. Final cleanup
    send_exaroton_command(f"kill @e[type=item,x=1296,y=78,z=-235,distance=..20]")

    # Save backup history
    history = {
        "status": "built",
        "min_x": MIN_X,
        "max_x": MAX_X,
        "min_z": MIN_Z,
        "max_z": MAX_Z
    }
    with open(BACKUP_FILE, "w") as f:
        json.dump(history, f, indent=4)

    print("Successfully built mini jungle biome and secured permissions!")
    return True

def undo(dry_run=False):
    if dry_run:
        print("[DRY-RUN] Would undo mini jungle biome.")
        return True

    # Revert to original grass / white concrete floor and plain biome (plains)
    cmds = [
        f"fill {MIN_X} 79 {MIN_Z} {MAX_X} 92 {MAX_Z} minecraft:air",
        f"fill {MIN_X} 78 {MIN_Z} {MAX_X} 78 {MAX_Z} minecraft:white_concrete",
        f"fillbiome {MIN_X} 78 {MIN_Z} {MAX_X} 92 {MAX_Z} minecraft:plains",
        f"kill @e[type=item,x=1296,y=78,z=-235,distance=..20]"
    ]
    for cmd in cmds:
        send_exaroton_command(cmd)

    if os.path.exists(BACKUP_FILE):
        os.remove(BACKUP_FILE)
    print("Undo complete.")
    return True

def main():
    parser = argparse.ArgumentParser(description="Convert farm to mini jungle and update permissions.")
    parser.add_argument("--dry-run", action="store_true", help="Preview commands without applying.")
    parser.add_argument("--undo", action="store_true", help="Revert the biome conversion.")
    args = parser.parse_args()

    if args.undo:
        undo(dry_run=args.dry_run)
    else:
        build_jungle(dry_run=args.dry_run)

if __name__ == "__main__":
    main()
