#Minecraft server properties
#Wed Aug 26 20:09:32 PKT 2026
accepts-transfers=true
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=true
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=true
management-server-host=0.0.0.0
management-server-port=9900
management-server-secret=QhzeL8Z7rtNp7aDHqTMC7RJ9oYfGGZsVMsr4isWf
management-server-tls-enabled=false
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=1000
max-tick-time=600000
max-world-size=29999984
motd=§4§l§mWELCOME §a§l§mTO §d§l§mSPEED §9§l§mRUN §4§l§mBY §f§l§mHANAN
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=5
prevent-proxy-connections=false
previews-chat=false
pvp=true
query.port=9898
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://packs.download/cEuS61sZvNEFS3aB/RDGqh5SeRJ63Ew62.zip
resource-pack-id=52444771-6835-5365-524a-363345773632
resource-pack-prompt=""
resource-pack-sha1=c7d3a0911135f2c1f873283faaa34879df46326c
server-ip=
server-port=62551
simulation-distance=3
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=3
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=6
white-list=false
